config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :authors
  resources :journals
  resources :articles
  resources :chapters
  resources :reports
end

app/models/journal.rb
# frozen_string_literal: true

class Journal < ApplicationRecord
  validates :name, presence: true
  validates :issn, presence: true, uniqueness: true, format: { with: /\A\d{4}-\d{3}[\dX]\z/ }
end

app/controllers/journals_controller.rb
# frozen_string_literal: true

class JournalsController < ApplicationController
  def index
    @journals = Journal.all
  end

  def new
    @journal = Journal.new
  end

  def create
    @journal = Journal.new(journal_params)

    if @journal.save
      redirect_to journal_path(@journal)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @journal = Journal.find(params[:id])
  end

  def edit
    @journal = Journal.find(params[:id])
  end

  def update
    @journal = Journal.find(params[:id])

    if @journal.update(journal_params)
      redirect_to @journal
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @journal = Journal.find(params[:id])

    @journal.destroy

    redirect_to journals_path
  end

  private

  def journal_params
    params.require(:journal).permit(:name, :issn)
  end
end

app/helpers/journals_helper.rb
# frozen_string_literal: true

module JournalsHelper
end

app/views/journals/_form.html.erb
<%= form_with(model: journal, data: { turbo: false }, class: "form-width-avg") do |form| %>
  <% if journal.errors.any? %>
    <div class="alert alert-danger">
      <h2>Ошибки: </h2>
      <ul>
        <% journal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row mb-3 w-50">
    <div class="col">
      <%= form.label :name, "Название" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row mb-3 w-50">
    <div class="col">
      <%= form.label :issn, "ISSN" %>
      <%= form.text_field :issn, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col">
      <%= form.submit text, class: "btn btn-success" %>
    </div>
  </div>
<% end %>

<div class="row mt-3">
  <div class="col">
    <% if journal.present? && journal.id.present? %>
      <%= link_to "Назад", journal_path(journal), class: "btn btn-outline-primary" %>
    <% else %>
      <%= link_to "Назад", journals_path, class: "btn btn-outline-primary" %>
    <% end %>
  </div>
</div>

app/views/journals/edit.html.erb
<h1 class="mt-3">Редактировать журнал</h1>

<%= render "form", journal: @journal, text: "Редактировать" %>

app/views/journals/index.html.erb
<h1 class="text-center my-3">Все журналы</h1>

<div class="container">
  <div class="row">
    <div class="col text-center">
        <%= link_to "Добавить новый журнал", new_journal_path, class: "btn btn-outline-success mb-3" %>
    </div>
  </div>
</div>

<div class="container-fluid">
  <% @journals.each do |journal| %>
    <div class="mt-3">
      <p>Название: <%= journal.name %></p>
      <%= link_to "Посмотреть информацию", journal_path(journal), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/journals/new.html.erb
<h1 class="mt-3">Создать новый журнал</h1>

<%= render "form", journal: @journal, text: "Создать" %>

app/views/journals/show.html.erb
<h2 class="mt-3">Журнал</h2>

<p>Название: <%= @journal.name %></p>
<p>ISSN: <%= @journal.issn %></p>

<%= link_to "Изменить информацию", edit_journal_path(@journal), class: "btn btn-outline-info mb-3" %>
<%= link_to "Удалить журнал", journal_path(@journal), data: { "turbo-method": :delete }, class: "btn btn-danger mb-3" %>
<%= link_to "Назад", journals_path, class: "btn btn-primary mb-3" %>