config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :authors
  resources :journals
  resources :articles
  resources :chapters
  resources :reports
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  has_many :author_reports, dependent: :destroy
  has_many :authors, through: :author_reports

  belongs_to :speaker, class_name: 'Author', foreign_key: 'speaker_id'

  validates :orig_name, :eng_name, :publish_date, :conference_name, :conference_location, :authors, presence: true
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  def index
    @reports = Report.all
  end

  def new
    @report = Report.new
    @authors = Author.all
  end

  def create
    @authors = Author.all
    @report = Report.new(report_params)

    if @report.save
      redirect_to report_path(@report)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @report = Report.find(params[:id])
    @author = Author.find(@report.speaker_id)
  end

  def edit
    @report = Report.find(params[:id])
    @authors = Author.all
  end

  def update
    @report = Report.find(params[:id])
    @authors = Author.all

    if @report.update(report_params)
      redirect_to @report
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @report = Report.find(params[:id])

    @report.destroy

    redirect_to reports_path
  end

  private

  def report_params
    params.require(:report).permit(:orig_name, :eng_name, :publish_date, :conference_name, :conference_location,
                                   :speaker_id, author_ids: [])
  end
end

app/helpers/reports_helper.rb
# frozen_string_literal: true

module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report, data: { turbo: false }, class: "form-width-avg") do |form| %>
  <% if report.errors.any? %>
    <div class="alert alert-danger">
      <h2>Ошибки: </h2>
      <ul>
        <% report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row mb-3 w-50">
    <div class="col">
      <%= form.label :orig_name, "Название на языке оригинала" %>
      <%= form.text_field :orig_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row mb-3 w-50">
    <div class="col">
      <%= form.label :eng_name, "Название на английском" %>
      <%= form.text_field :eng_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row mb-3 w-50">
    <div class="col">
      <%= form.label :publish_date, "Дата публикации" %>
      <%= form.date_field :publish_date, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row mb-3 w-50">
    <div class="col">
      <%= form.label :conference_name, "Название конференции" %>
      <%= form.text_field :conference_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row mb-3 w-50">
    <div class="col">
      <%= form.label :conference_location, "Место проведения конференции" %>
      <%= form.select :conference_location, ["Локальная", "Международная", "Заграничная"], class: "form-select" %>
    </div>
  </div>

  <div class="form-group row mb-3 w-50">
    <div class="col">
      <%= form.label :speaker_id, "Докладчик" %>
      <%= form.select :speaker_id, authors.map { |a| [a.fullname, a.id] }, class: "form-select" %>
    </div>
  </div>

  <div class="form-group row mb-3 w-50">
    <div class="col">
      <%= form.label :author_ids, "Авторы (зажмите Ctrl для выбора нескольких)" %>
      <%= form.select :author_ids, authors.map { |a| [a.fullname, a.id] }, {}, multiple: true, class: "form-select" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col">
      <%= form.submit text, class: "btn btn-success" %>
    </div>
  </div>
<% end %>

<div class="row mt-3">
  <div class="col">
    <% if report.present? && report.id.present? %>
      <%= link_to "Назад", report_path(report), class: "btn btn-outline-primary" %>
    <% else %>
      <%= link_to "Назад", reports_path, class: "btn btn-outline-primary" %>
    <% end %>
  </div>
</div>

app/views/reports/edit.html.erb
<h1 class="mt-3">Редактировать доклад</h1>

<%= render "form", report: @report, authors: @authors, text: "Редактировать" %>

app/views/reports/index.html.erb
<h1 class="text-center mt-3">Все доклады</h1>

<div class="container">
  <div class="row">
    <div class="col text-center">
        <%= link_to "Добавить новый доклад", new_report_path, class: "btn btn-outline-success mb-3" %>
    </div>
  </div>
</div>

<div class="container-fluid">
  <% @reports.each do |report| %>
    <div class="mt-3">
      <p>Название: <%= report.orig_name %></p>
      <%= link_to "Посмотреть информацию", report_path(report), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/reports/new.html.erb
<h1 class="mt-3">Создать новый доклад</h1>

<%= render "form", report: @report, authors: @authors, text: "Создать" %>

app/views/reports/show.html.erb
<h2 class="mt-3">Доклад "<%= @report.orig_name%>"</h2>

<p>Название на языке оригинала: <%= @report.orig_name %></p>
<p>Название на английском: <%= @report.eng_name %></p>
<p>Дата публикации: <%= @report.publish_date %></p>
<p>Название конференции: <%= @report.conference_name %></p>
<p>Место проведения конференции: <%= @report.conference_location %></p>
<p>Докладчик: <%= @author.fullname %></p>
<p>Авторы: </p>
<% @report.authors.each do |author| %>
  <p><%= author.fullname %></p>
<% end %>

<%= link_to "Изменить информацию", edit_report_path(@report), class: "btn btn-outline-info mb-3" %>
<%= link_to "Удалить доклад", report_path(@report), data: { "turbo-method": :delete }, class: "btn btn-danger mb-3" %>
<%= link_to "Назад", reports_path, class: "btn btn-primary mb-3" %>