config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :authors
  resources :journals
  resources :articles
  resources :chapters
  resources :reports
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Публикации организации</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav w-100">
        <li class="nav-item">
          <%= link_to "Авторы", authors_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Журналы", journals_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Статьи", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Главы книг", chapters_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Доклады", reports_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Publications</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>